const cities = [
    'London',
    'Paris',
    'Berlin',
    'Amsterdam',
    'Rome',
    'Florence',
    'Barcelona',
    'Prague',
    'Zurich',
    'Athens',
    'New York',
    'Tokyo',
    'Lisbon',
    'Honolulu',
    'Istanbul',
    'Bangkok',
    'Agra',
    'Cairo',
    'Helsinki',
    'Bali',
    'Shanghai',
    'Las Vegas',
    'Jerusalem',
    'Venice',
    'Cape Town',
    'Rio de Janeiro',
    'Singapore',
    'Toronto',
    'Seoul',
    'Casablanca',
    'Moscow',
    'Sydney',
    'Lima',
    'Beijing',
    'Buenos Aires',
    'Edinburgh',
    'Los Angeles',
    'Copenhagen',
    'Osaka',
    'Auckland',
    'Mumbai',
    'Dubai',
    'Munich',
    'Hong Kong',
    'Qatar',
    'Seattle',
    'Oslo',
    'Bath',
    'Vienna',
    'Madrid'
];

module.exports = cities;
